[package]
name = "autopush_common"
version = "1.0.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[lib]
name = "autopush_common"

[dependencies]
cadence = "0.19.1"
chrono = "0.4.10"
config = "0.10.1"
error-chain = "0.12.2"
futures = { version = "0.3.4", features = ["compat"] }
#futures = { version = "0.1" }
futures-backoff = "0.1.0"
httparse = "1.3.4"
hyper = "0.13"
lazy_static = "1.4.0"
log = { version = "0.4.8", features = ["max_level_info", "release_max_level_info"] }
mozsvc-common = "0.1.1"
rand = "0.7.3"
regex = "1.3.4"
reqwest = "0.10"
rusoto_core = "0.42"
rusoto_credential = "0.42"
rusoto_dynamodb = "0.42"
sentry = { version = "0.18.0", features = ["with_error_chain"] }
serde = "1.0.104"
serde_derive = "1.0.104"
serde_dynamodb = "0.4.1"
serde_json = "1.0.48"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.4.0"
slog-term = "2.5.0"
slog-mozlog-json = "0.1.0"
slog-scope = "4.3.0"
slog-stdlog = "4.0.0"
tokio = "0.2"
# XXX: pin to < 0.10 until hyper 0.13
tungstenite = { version = "0.9.2", default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
