[package]
name = "autopush_common"
# Should match version in ../autopush/Cargo.toml
version = "1.57.3"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[lib]
name = "autopush_common"

[dependencies]
base64 = "0.12.1"
cadence = "0.20.0"
chrono = "0.4.11"
config = "0.10.1"
error-chain = "0.12.2"
fernet = "0.1.3"
# XXX: pin to 0.1 until likely hyper 0.13
futures = "0.1.29"
futures-backoff = "0.1.0"
hex = "0.4.2"
httparse = "1.3.4"
# XXX: pin to hyper 0.12 for now: 0.13 has many changes..
hyper = "0.12"
lazy_static = "1.4.0"
log = { version = "0.4.8", features = ["max_level_info", "release_max_level_info"] }
mozsvc-common = "0.1.1"
openssl = "0.10.29"
rand = "0.7.3"
regex = "1.3.9"
# XXX: pin to < 0.10 until futures 0.3
reqwest = "0.9.24"
rusoto_core = "0.42.0"
rusoto_credential = "0.42.0"
rusoto_dynamodb = "0.42.0"
sentry = { version = "0.18.1", features = ["with_error_chain"] }
serde = "1.0.111"
serde_derive = "1.0.111"
serde_dynamodb = "0.4.1"
serde_json = "1.0.53"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.5.0"
slog-term = "2.6.0"
slog-mozlog-json = "0.1.0"
slog-scope = "4.3.0"
slog-stdlog = "4.0.0"
smallvec = "1.6"  # for RUSTSEC-2021-0003
tokio-core = "0.1.17"
# XXX: pin to < 0.10 until hyper 0.13
tungstenite = { version = "0.9.2", default-features = false }
url = "2.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
