[package]
name = "autopush_common"
# Should match version in ../autopush/Cargo.toml
version = "1.57.8"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[lib]
name = "autopush_common"

[dependencies]
base64 = "0.13"
cadence = "0.25"
chrono = "0.4"
config = "0.11"
error-chain = "0.12"
fernet = "0.1.3"
futures = "0.1.29" # 0.1.30 requires hyper 0.13+
futures-backoff = "0.1.0"
hex = "0.4.2"
httparse = "1.3"
hyper = "^0.12.36" # 0.13+ requires too many changes
lazy_static = "1.4.0"
log = { version = "0.4", features = ["max_level_info", "release_max_level_info"] }
mozsvc-common = "0.1.1"
openssl = "0.10"
rand = "0.8"
regex = "1.4"
reqwest = "0.9.24"  # 0.10+ requires futures 0.3+
rusoto_core = "0.42.0"  # 0.46+ requires futures 0.3+
rusoto_credential = "0.42.0"  # 0.46+ requires futures 0.3+
rusoto_dynamodb = "0.42.0"  # 0.46+ requires futures 0.3+
sentry = { version = "0.19", features = ["with_error_chain"] }  # 0.20+ requires new sentry server
serde = "1.0"
serde_derive = "1.0"
serde_dynamodb = "0.4.1"  # 0.7+ requires rusoto 0.46+
serde_json = "1.0"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.6.0"
slog-term = "2.6.0"
slog-mozlog-json = "0.1.0"
slog-scope = "4.4.0"
slog-stdlog = "4.1.0"
smallvec = "1.6"  # for RUSTSEC-2021-0003
tokio-core = "0.1.17"
tungstenite = { version = "0.9.2", default-features = false } # 0.10+  requires hyper 0.13+
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
