[package]
name = "autoendpoint"
version = "1.0.0"
authors = ["Mark Drobnak <mdrobnak@mozilla.com>", "jrconlin <me+crypt@jrconlin.com>"]
edition = "2018"

[dependencies]
actix-http = "1.0"
actix-web = "2.0"
actix-rt = "1.0"
actix-cors = "0.2.0"
autopush_common = { path = "../autopush-common" }
backtrace = "0.3"
base64 = "0.12.1"
cadence = "0.20"
config = "0.10.1"
docopt = "1.1.0"
fernet = "0.1.3"
futures = { version = "0.3", features = ["compat"] }
hex = "0.4.2"
jsonwebtoken = "7.1.1"
lazy_static = "1.4.0"
openssl = "0.10"
regex = "1.3"
sentry = { version = "0.18", features = ["with_curl_transport"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_error", "dynamic-keys"] }
slog-async = "2.4"
slog-envlogger = "2.2.0"
slog-mozlog-json = "0.1"
slog-scope = "4.3"
slog-stdlog = "4.0"
slog-term = "2.5"
thiserror = "1.0"
url = "2.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
validator = "0.10.0"
validator_derive = "0.10.0"
