[package]
name = "autoendpoint"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
fernet.workspace = true

# Using a fork temporarily until these three PRs are merged:
# - https://github.com/pimeys/a2/pull/49
# - https://github.com/pimeys/a2/pull/48
# - https://github.com/pimeys/a2/pull/47
# The `autoendpoint` branch merges these three PRs together.
# The version of a2 at the time of the fork is v0.5.3.
a2 = { git = "https://github.com/mozilla-services/a2.git", branch = "autoendpoint" }
# several of these libraries are pinned due to https://github.com/mozilla-services/autopush-rs/issues/249
actix-web = "3.3"
actix-rt = "1.1"   # 2.0+ requires futures 0.3+
actix-cors = "0.5"
actix-http = "3.0"
again = { version = "0.1.2", default-features = false, features = ["log", "rand"] }
async-trait = "0.1"
autopush_common = { path = "../autopush-common" }
backtrace = "0.3"
cadence = "0.29"
config = "0.13"
docopt = "1.1.0"
futures = "0.3"
hex = "0.4.2"
jsonwebtoken = "8.0"
lazy_static = "1.4.0"
log = "0.4"
openssl = "0.10"
rand = "0.8"
regex = "1.4"
reqwest = "0.10.6"  # 0.11+ requires futures 0.3+
rusoto_core = "0.45.0"  # 0.46+ requires futures 0.3+
rusoto_dynamodb = "0.45.0"  # 0.46+ requires futures 0.3+
# Using debug-logs avoids https://github.com/getsentry/sentry-rust/issues/237
sentry.workspace = true
# sentry = { version = "0.19", features = ["debug-logs"] }  # Keep on 0.19 in order to work with our backend
serde = { version = "1.0", features = ["derive"] }
serde_dynamodb = "0.6"  # 0.7+ requires rusoto_dynamodb 0.46+
serde_json = "1.0"
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-mozlog-json.workspace = true
slog-scope.workspace = true
slog-stdlog.workspace = true
slog-term.workspace = true

smallvec = "1.6"  # for RUSTSEC-2021-0003
tokio = { version = "0.2", features = ["fs"] }  # 1.1+ requires futures 0.3+
thiserror = "1.0"
url = "2.2"
uuid = { version = "1.1", features = ["serde", "v4"] }
validator = "0.16"
validator_derive = "0.16"
yup-oauth2 = "4.1.2"  # 5.0+ requires tokio 1.1+

# For mockito test debugging
#ureq={ version="2.4", features=["json"] }

[dev-dependencies]
mockall = "0.8.3"  # 0.9+ requires reworking tests
mockito = "0.31"
tempfile = "3.2.0"
tokio = { version = "0.2", features = ["macros"] }
