[package]
name = "autoendpoint"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
cadence.workspace = true
config.workspace = true
docopt.workspace = true
fernet.workspace = true
hex.workspace = true
lazy_static.workspace = true
log.workspace = true
openssl.workspace = true
rand.workspace = true
regex.workspace = true
sentry.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-mozlog-json.workspace = true
slog-scope.workspace = true
slog-stdlog.workspace = true
slog-term.workspace = true
smallvec.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

# Using a fork temporarily until these three PRs are merged:
# - https://github.com/pimeys/a2/pull/49
# - https://github.com/pimeys/a2/pull/48
# - https://github.com/pimeys/a2/pull/47
# The `autoendpoint` branch merges these three PRs together.
# The version of a2 at the time of the fork is v0.5.3.
a2 = { git = "https://github.com/mozilla-services/a2.git", branch = "autoendpoint" }
# several of these libraries are pinned due to https://github.com/mozilla-services/autopush-rs/issues/249
actix-web = "3.3"
actix-rt = "1.1"   # 2.0+ requires futures 0.3+
actix-cors = "0.5"
again = { version = "0.1.2", default-features = false, features = ["log", "rand"] }
async-trait = "0.1"
autopush_common = { path = "../autopush-common" }
backtrace = "0.3"
futures = "0.3"
jsonwebtoken = "8.0"
reqwest = { version="0.10.6", features = ["json"]}  # 0.11+ requires futures 0.3+
rusoto_core = "0.45.0"  # 0.46+ requires futures 0.3+
rusoto_dynamodb = "0.45.0"  # 0.46+ requires futures 0.3+
serde_dynamodb = "0.6"  # 0.7+ requires rusoto_dynamodb 0.46+
tokio = { version = "0.2", features = ["fs"] }  # 1.1+ requires futures 0.3+
validator = "0.16"
validator_derive = "0.16"
yup-oauth2 = "4.1.2"  # 5.0+ requires tokio 1.1+

# For mockito test debugging
#ureq={ version="2.4", features=["json"] }

[dev-dependencies]
mockall = "0.8.3"  # 0.9+ requires reworking tests
mockito = "0.31"
tempfile = "3.2.0"
tokio = { version = "0.2", features = ["macros"] }
