[package]
name = "autoendpoint"
# Should match version in ../autopush/Cargo.toml
version = "1.57.3"
authors = ["Mark Drobnak <mdrobnak@mozilla.com>", "jrconlin <me+crypt@jrconlin.com>"]
edition = "2018"

[dependencies]
# Using a fork temporarily until these three PRs are merged:
# - https://github.com/pimeys/a2/pull/49
# - https://github.com/pimeys/a2/pull/48
# - https://github.com/pimeys/a2/pull/47
# The `autoendpoint` branch merges these three PRs together.
# The version of a2 at the time of the fork is v0.5.3.
a2 = { git = "https://github.com/mozilla-services/a2.git", branch = "autoendpoint" }
# several of these libraries are pinned due to https://github.com/mozilla-services/autopush-rs/issues/249
actix-web = "3.2"  # 3.3+ requires futures 0.3+
actix-rt = "1.1"   # 2.0+ requires futures 0.3+
actix-cors = "0.5"
again = { version = "0.1.2", default-features = false, features = ["log"] }
async-trait = "0.1"
autopush_common = { path = "../autopush-common" }
backtrace = "0.3"
base64 = "0.13"
cadence = "0.24"
config = "0.10.1"
docopt = "1.1.0"
fernet = "0.1.3"
futures = "0.3"
hex = "0.4.2"
jsonwebtoken = "7.2"
lazy_static = "1.4.0"
log = "0.4"
openssl = "0.10"
regex = "1.4"
reqwest = "0.10.6"  # 0.11+ requires futures 0.3+
rusoto_core = "0.45.0"  # 0.46+ requires futures 0.3+
rusoto_dynamodb = "0.45.0"  # 0.46+ requires futures 0.3+
# Using debug-logs avoids https://github.com/getsentry/sentry-rust/issues/237
sentry = { version = "0.20", features = ["debug-logs"] }  # 0.22+ requires tokio 1.1+
serde = { version = "1.0", features = ["derive"] }
serde_dynamodb = "0.6"  # 0.7+ requires rusoto_dynamodb 0.46+
serde_json = "1.0"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_error", "dynamic-keys"] }
slog-async = "2.6"
slog-envlogger = "2.2.0"
slog-mozlog-json = "0.1"
slog-scope = "4.4"
slog-stdlog = "4.1"
slog-term = "2.6"
tokio = { version = "0.2", features = ["fs"] }  # 1.1+ requires futures 0.3+
thiserror = "1.0"
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
validator = "0.12"
validator_derive = "0.12"
yup-oauth2 = "4.1.2"  # 5.0+ requires tokio 1.1+

[dev-dependencies]
mockall = "0.8.3"  # 0.9+ requires reworking tests
mockito = "0.29.0"
tempfile = "3.2.0"
tokio = { version = "0.2", features = ["macros"] }
